version: "3.8"

services:
  music-unlocker:
    image: music-unlocker:latest
    build: .
    container_name: music-unlocker
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - ENV=production
